enum actionTypes {
    // GET CART
    GET_CART_REQUEST = "GET_CART_REQUEST",
    GET_CART_SUCCESS = "GET_CART_SUCCESS",
    GET_CART_ERROR = "GET_CART_ERROR",

    // ADD TO CART
    ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST",
    ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS",
    ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR",

    // DELETE FROM CART
    DELETE_FROM_CART_REQUEST = "DELETE_FROM_CART_REQUEST",
    DELETE_FROM_CART_SUCCESS = "DELETE_FROM_CART_SUCCESS",
    DELETE_FROM_CART_ERROR = "DELETE_FROM_CART_ERROR",

    // CLEAR CART
    CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST",
    CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS",
    CLEAR_CART_ERROR = "CLEAR_CART_ERROR",
};

export default actionTypes
