enum actionTypes {
    GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST",
    GET_PRODUCTS_ERROR = "GET_PRODUCTS_ERROR",

    GET_ONE_PRODUCT_REQUEST = "GET_ONE_PRODUCT_REQUEST",
    GET_ONE_PRODUCT_SUCCESS = "GET_ONE_PRODUCT_SUCCESS",
    GET_ONE_PRODUCT_ERROR = "GET_ONE_PRODUCT_ERROR",

    DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST",
    DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS",
    DELETE_PRODUCT_ERROR = "DELETE_PRODUCT_ERROR",

    ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST",
    ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS",
    ADD_PRODUCT_ERROR = "ADD_PRODUCT_ERROR",

    EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST",
    EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS",
    EDIT_PRODUCT_ERROR = "EDIT_PRODUCT_ERROR",
};

export default actionTypes